import request from 'supertest';
import { describe, it, expect, afterAll } from 'vitest';
import { vi } from 'vitest';
vi.mock('../server/licence',()=>({licenseGuard:(_req:any,_res:any,next:any)=>next(),licenceStatus:async()=>({tier:'TEST'}),verifyLicence:()=>null}));
import { app } from '../server';
import { prisma } from '../server/db';

const enabled = process.env.RUN_DATABASE_TESTS === '1';
describe.skipIf(!enabled)('CRM persistence and tenant isolation', () => {
  afterAll(async () => { await prisma.$disconnect(); });
  it('registers two companies, persists edits, enforces roles and isolates their records', async () => {
    const stamp = Date.now();
    const a = request.agent(app), b = request.agent(app);
    const input = (suffix: string) => ({ name: 'Test Owner', organizationName: `Test ${suffix}`, organizationSlug: `test-${suffix}-${stamp}`, email: `${suffix}-${stamp}@example.test`, password: 'TestPassword12345!' });
    const regA = await a.post('/api/auth/register').send(input('a'));
    expect(regA.status, JSON.stringify(regA.body)).toBe(201);
    const orgA = regA.body.organization.id;
    const regB = await b.post('/api/auth/register').send(input('b'));
    expect(regB.status, JSON.stringify(regB.body)).toBe(201);
    const orgB = regB.body.organization.id;
    expect((await request(app).get('/api/ready')).status).toBe(200);
    expect((await a.get('/api/auth/me').set('x-organization-id',orgA)).body.user.email).toBe(input('a').email);
    expect((await a.get('/api/crm/contacts').set('x-organization-id',orgB)).status).toBe(401);
    const contact = await a.post('/api/crm/contacts').set('x-organization-id',orgA).send({ firstName:'Ana',email:'ana@example.test', tags:['prueba'] });
    expect(contact.status).toBe(201);
    const id = contact.body.item.id;
    expect((await a.patch(`/api/crm/contacts/${id}`).set('x-organization-id',orgA).send({ firstName:'Ana María',phone:'8095550101' })).status).toBe(200);
    const saved = await a.get('/api/crm/contacts').set('x-organization-id',orgA);
    expect(saved.body.items[0].firstName).toBe('Ana María');
    expect(saved.body.items[0].tags).toEqual(['prueba']);
    expect((await b.get('/api/crm/contacts').set('x-organization-id',orgB)).body.items).toEqual([]);
    expect((await b.patch(`/api/crm/contacts/${id}`).set('x-organization-id',orgB).send({ firstName:'Intruder' })).status).toBe(404);
    const product = await a.post('/api/crm/products').set('x-organization-id',orgA).send({ name:'Servicio',sku:'', price:1000 });
    expect(product.status).toBe(201);
    expect((await a.post('/api/crm/products').set('x-organization-id',orgA).send({ name:'Servicio 2',sku:'',price:200 })).status).toBe(201);
    expect((await a.patch(`/api/operations/products/${product.body.item.id}`).set('x-organization-id',orgA).send({ price:1500,active:false })).status).toBe(200);
    const company = await a.post('/api/operations/companies').set('x-organization-id',orgA).send({ name:'Cliente SA' });
    expect(company.status).toBe(201);
    const pipelines = await a.get('/api/crm/pipelines').set('x-organization-id',orgA);
    const pipeline = pipelines.body.items[0];
    const dealInput = { title:'Venta',value:1500,pipelineId:pipeline.id,stageId:pipeline.stages[0].id,contactId:id,companyId:company.body.item.id,productId:product.body.item.id };
    const deal = await a.post('/api/crm/deals').set('x-organization-id',orgA).send(dealInput);
    expect(deal.status, JSON.stringify(deal.body)).toBe(201);
    const otherPipeline = (await b.get('/api/crm/pipelines').set('x-organization-id',orgB)).body.items[0];
    expect((await b.post('/api/crm/deals').set('x-organization-id',orgB).send({ ...dealInput,pipelineId:otherPipeline.id,stageId:otherPipeline.stages[0].id })).status).toBe(400);
    expect((await a.patch(`/api/operations/deals/${deal.body.item.id}`).set('x-organization-id',orgA).send({ stageId:otherPipeline.stages[0].id })).status).toBe(400);
    expect((await a.patch(`/api/operations/deals/${deal.body.item.id}`).set('x-organization-id',orgA).send({ status:'WON',stageId:pipeline.stages[4].id })).status).toBe(200);
    const activity = await a.post('/api/operations/activities').set('x-organization-id',orgA).send({ title:'Llamar',type:'CALL',contactId:id,dueAt:new Date().toISOString() });
    expect(activity.status).toBe(201);
    expect((await b.post('/api/operations/activities').set('x-organization-id',orgB).send({ title:'Intruder',type:'TASK',contactId:id })).status).toBe(400);
    expect((await a.patch(`/api/operations/activities/${activity.body.item.id}`).set('x-organization-id',orgA).send({ completedAt:new Date().toISOString() })).status).toBe(200);
    expect((await a.get('/api/operations/activities').set('x-organization-id',orgA)).body.items[0].completedAt).toBeTruthy();
    expect((await a.get('/api/crm/dashboard').set('x-organization-id',orgA)).body.metrics.wonDeals).toBe(1);
    expect((await a.get('/api/crm/dashboard').set('x-organization-id',orgA)).body.metrics.collectedRevenue).toBe(0);
    expect((await b.post('/api/platform/payments/sandbox').set('x-organization-id',orgB).send({ contactId:id,amount:100 })).status).toBe(400);
    const member = await a.post('/api/operations/team').set('x-organization-id',orgA).send({ name:'Viewer',email:`viewer-${stamp}@example.test`,password:'ViewerPassword123!',role:'VIEWER' });
    expect(member.status).toBe(201);
    const viewer = request.agent(app);
    expect((await viewer.post('/api/auth/login').send({email:`viewer-${stamp}@example.test`,password:'ViewerPassword123!'})).status).toBe(200);
    expect((await viewer.get('/api/crm/contacts').set('x-organization-id',orgA)).status).toBe(200);
    expect((await viewer.post('/api/crm/contacts').set('x-organization-id',orgA).send({firstName:'Forbidden'})).status).toBe(403);
    expect((await viewer.get('/api/operations/team').set('x-organization-id',orgA)).status).toBe(403);
    expect((await a.patch(`/api/operations/team/${member.body.item.id}`).set('x-organization-id',orgA).send({active:false})).status).toBe(200);
    expect((await viewer.get('/api/crm/contacts').set('x-organization-id',orgA)).status).toBe(401);
    expect((await a.post('/api/crm/contacts').set('origin','https://evil.invalid').set('x-organization-id',orgA).send({firstName:'CSRF'})).status).toBe(403);
    expect((await a.patch('/api/operations/organization').set('x-organization-id',orgA).send({name:'Nueva empresa',currency:'USD',timezone:'America/Santo_Domingo'})).status).toBe(200);
    expect((await a.get('/api/platform/organization').set('x-organization-id',orgA)).body.organization.name).toBe('Nueva empresa');
    expect((await a.get('/api/operations/audit').set('x-organization-id',orgA)).body.items.length).toBeGreaterThan(5);
    expect((await a.post('/api/operations/password').set('x-organization-id',orgA).send({current:input('a').password,password:'NewPassword12345!'})).status).toBe(200);
    expect((await a.get('/api/crm/contacts').set('x-organization-id',orgA)).status).toBe(401);
    expect((await a.post('/api/auth/login').send({email:input('a').email,password:'NewPassword12345!'})).status).toBe(200);
    expect((await a.post('/api/auth/logout')).status).toBe(200);
    expect((await a.get('/api/crm/contacts').set('x-organization-id',orgA)).status).toBe(401);
  }, 60000);
});
