import {getAgentCatalogue} from '../server/course-knowledge';
import {processSocialEvent,normalizeEvents} from '../server/social';
import request from 'supertest';
import {describe,it,expect,afterAll,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {sign,randomUUID,createHmac} from 'node:crypto';
import {app} from '../server';
import {prisma} from '../server/db';
import {verifyLicence} from '../server/licence';
const mockedGenerate=vi.hoisted(()=>vi.fn());
vi.mock('@google/genai',()=>({GoogleGenAI:class {models={generateContent:mockedGenerate}},Type:{OBJECT:'OBJECT',STRING:'STRING',NUMBER:'NUMBER',ARRAY:'ARRAY',BOOLEAN:'BOOLEAN'}}));
const enabled=process.env.RUN_DATABASE_TESTS==='1'&&!!process.env.TEST_LICENSE_PRIVATE_KEY_PATH;
const signed=(organizationId:string,tier='COMMERCIAL',expiresAt=new Date(Date.now()+86400000).toISOString())=>{
 const key=readFileSync(process.env.TEST_LICENSE_PRIVATE_KEY_PATH!,'utf8');
 const body=Buffer.from(JSON.stringify({organizationId,tier,expiresAt:tier==='INTECA_LIFETIME'?null:expiresAt})).toString('base64url');
 return body+'.'+sign(null,Buffer.from(body),key).toString('base64url');
};
describe.skipIf(!enabled)('Connected workspace v0.4 with real license enforcement',()=>{
 afterAll(async()=>{vi.restoreAllMocks();await prisma.$disconnect();});
 it('enforces signed licenses; persists workflows, chat, agents, payments, files and tenant isolation',async()=>{
  const stamp=Date.now();const a=request.agent(app),b=request.agent(app);
  const register=async(agent:any,suffix:string)=>{const r=await agent.post('/api/auth/register').send({name:'Test Owner',organizationName:'Enterprise '+suffix,organizationSlug:`workspace-${suffix}-${stamp}`,email:`workspace-${suffix}-${stamp}@example.test`,password:'WorkspacePassword123!'});expect(r.status,JSON.stringify(r.body)).toBe(201);return r.body.organization.id;};
  const orgA=await register(a,'a'),orgB=await register(b,'b');
  const post=(url:string,body:any)=>a.post('/api/workspace'+url).set('x-organization-id',orgA).send(body);
  expect((await post('/agents',{name:'Test',role:'Sales',systemPrompt:'Only approved facts'})).status).toBe(402);
  expect((await post('/license/activate',{token:signed(orgB)})).status).toBe(400);
  expect((await post('/license/activate',{token:signed(orgA,'COMMERCIAL','2000-01-01')})).status).toBe(400);
  expect((await post('/license/activate',{token:signed(orgA,'INTECA_LIFETIME')})).status).toBe(200);
  expect((await b.post('/api/workspace/license/activate').set('x-organization-id',orgB).send({token:signed(orgB)})).status).toBe(200);
  expect(verifyLicence(signed(orgA)+'tamper',orgA)).toBe(null);
  expect((await post('/workflows',{name:'Welcome',active:true,delayHours:24,title:'Call new contact'})).status).toBe(201);
  const contact=await a.post('/api/crm/contacts').set('x-organization-id',orgA).send({firstName:'Ana',email:'ana@example.test'});expect(contact.status).toBe(201);
  const activities=await a.get('/api/operations/activities').set('x-organization-id',orgA);expect(activities.body.items.some((x:any)=>x.title==='Call new contact')).toBe(true);
  const agent=await post('/agents',{name:'Consultor',role:'Ventas',systemPrompt:'Usa solo precios autorizados',active:true});expect(agent.status).toBe(201);
  expect((await b.patch('/api/workspace/agents/'+agent.body.item.id).set('x-organization-id',orgB).send({name:'Intruder'})).status).toBe(404);
  const conv=await post('/conversations',{contactId:contact.body.item.id,channel:'MANUAL'});expect(conv.status).toBe(201);
  const msg=await post('/conversations/'+conv.body.item.id+'/messages',{direction:'OUTBOUND',content:'Propuesta aprobada'});expect(msg.status).toBe(201);expect(msg.body.item.status).toBe('DRAFT');
  expect((await b.post('/api/workspace/conversations/'+conv.body.item.id+'/messages').set('x-organization-id',orgB).send({direction:'INBOUND',content:'Intruder'})).status).toBe(404);
  const payInput={contactId:contact.body.item.id,amount:1500,currency:'DOP',reference:'Pago curso',method:'TRANSFER',status:'PENDING',idempotencyKey:randomUUID()};
  const payment=await post('/payments',payInput);expect(payment.status).toBe(201);
  const replay=await post('/payments',payInput);expect(replay.body.item.id).toBe(payment.body.item.id);
  expect((await a.patch('/api/workspace/payments/'+payment.body.item.id).set('x-organization-id',orgA).send({status:'REFUNDED'})).status).toBe(409);
  expect((await a.patch('/api/workspace/payments/'+payment.body.item.id).set('x-organization-id',orgA).send({status:'COMPLETED'})).status).toBe(200);
  const doc=await post('/documents',{name:'test.txt',mimeType:'text/plain',base64:Buffer.from('private document').toString('base64')});expect(doc.status).toBe(201);
  const download=await a.get('/api/workspace/documents/'+doc.body.item.id+'/download').set('x-organization-id',orgA);expect(download.status).toBe(200);expect(download.body.toString()).toBe('private document');
  expect((await b.get('/api/workspace/documents/'+doc.body.item.id+'/download').set('x-organization-id',orgB)).status).toBe(404);
  expect((await post('/documents',{name:'attack.html',mimeType:'text/html',base64:'aA=='})).status).toBe(400);
  expect((await post('/campaigns',{name:'Campaña',channel:'EMAIL',audience:{description:'Interesados'},content:{text:'Contenido real'},scheduledAt:null})).status).toBe(201);
  expect((await post('/ai',{prompt:'Hola',agentId:agent.body.item.id})).status).toBe(503);
  const config=await a.put('/api/workspace/connections/RESEND').set('x-organization-id',orgA).send({apiKey:'re_test_secret_for_tests',from:'ventas@example.test'});expect(config.status).toBe(200);
  const row=await prisma.integrationConnection.findUniqueOrThrow({where:{organizationId_provider:{organizationId:orgA,provider:'RESEND'}}});expect(row.encryptedConfig).not.toContain('re_test_secret_for_tests');
  const mock=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify({id:'mock-provider-id'}),{status:200,headers:{'Content-Type':'application/json'}}));
  const sent=await post('/messages/'+msg.body.item.id+'/send-email',{subject:'Consulta',confirm:true});expect(sent.status).toBe(200);
  expect((await post('/messages/'+msg.body.item.id+'/send-email',{subject:'Consulta',confirm:true})).status).toBe(409);expect(mock).toHaveBeenCalledTimes(1);mock.mockRestore();
  const policy=await a.put('/api/workspace/sales-policy').set('x-organization-id',orgA).send({website:'https://example.test',businessContext:'Horario autorizado',salesPlaybook:'Preguntar la necesidad',handoffEmail:'sales@example.test',checkoutUrl:'',dailyAiLimit:3,enabled:true});expect(policy.status).toBe(200);
  const widget=await request(app).post('/api/website/'+orgA+'/'+policy.body.settings.widgetKey+'/chat').send({name:'Visitor',email:'visitor@example.test',consent:true,message:'Hola'});expect(widget.status).toBe(503);
  // Customer payment portal: uploaded proof never marks a request paid.
  expect((await a.put('/api/workspace/payment-methods').set('x-organization-id',orgA).send({instructions:'Use reference',banks:[{bank:'Banco de prueba',holder:'Empresa A',account:'123456',accountType:'Ahorros',currency:'DOP'}],gateways:[{name:'Checkout prueba',url:'https://example.test/pay'}]})).status).toBe(200);
  const paymentRequest=await post('/payment-requests',{contactId:contact.body.item.id,amount:2500,currency:'DOP',description:'Inscripción',days:7});expect(paymentRequest.status).toBe(201);
  const paymentToken=paymentRequest.body.item.token,requestId=paymentRequest.body.item.id;
  const portal=await request(app).get('/api/pay/'+paymentToken);expect(portal.status).toBe(200);expect(portal.body.methods.banks[0].account).toBe('123456');expect(portal.body).not.toHaveProperty('contactId');
  const proof={payerName:'Ana Prueba',reference:'ABC123',name:'comprobante.pdf',mimeType:'application/pdf',base64:Buffer.from('%PDF-1.4 mock test fixture').toString('base64')};
  expect((await request(app).post('/api/pay/'+paymentToken+'/proof').send({...proof,base64:Buffer.from('not pdf').toString('base64')})).status).toBe(400);
  expect((await request(app).post('/api/pay/'+paymentToken+'/proof').send(proof)).status).toBe(201);
  expect((await request(app).post('/api/pay/'+paymentToken+'/proof').send(proof)).status).toBe(409);
  expect((await prisma.paymentRequest.findUniqueOrThrow({where:{id:requestId}})).status).toBe('PROOF_RECEIVED');
  expect(await prisma.payment.count({where:{organizationId:orgA,idempotencyKey:'request-'+requestId}})).toBe(0);
  const review={decision:'APPROVE',note:'Abono verificado en banco de prueba',confirm:true};
  expect((await b.post('/api/workspace/payment-requests/'+requestId+'/review').set('x-organization-id',orgB).send(review)).status).toBe(404);
  expect((await post('/payment-requests/'+requestId+'/review',review)).status).toBe(200);
  expect((await post('/payment-requests/'+requestId+'/review',review)).status).toBe(409);
  expect(await prisma.payment.count({where:{organizationId:orgA,idempotencyKey:'request-'+requestId}})).toBe(1);
  const proofDoc=await prisma.document.findFirstOrThrow({where:{ownerEntity:'PaymentRequest',ownerEntityId:requestId}});
  // Official-provider webhooks: verify signature, account routing, deduplication and manual mode.
  const credentials={accessToken:'test-access-token-never-live',appSecret:'test-app-secret-private',verifyToken:'test-verify-token-private',accountId:'12345',apiVersion:'v23.0',autoReply:false,agentId:agent.body.item.id};
  expect((await a.put('/api/workspace/connections/WHATSAPP').set('x-organization-id',orgA).send(credentials)).status).toBe(200);
  const endpoint='/api/channels/'+orgA+'/WHATSAPP';
  expect((await request(app).get(endpoint).query({'hub.mode':'subscribe','hub.verify_token':credentials.verifyToken,'hub.challenge':'abc'})).text).toBe('abc');
  expect((await request(app).get(endpoint).query({'hub.mode':'subscribe','hub.verify_token':'bad'})).status).toBe(403);
  const payload={entry:[{changes:[{value:{metadata:{phone_number_id:'12345'},messages:[{id:'wamid-test-1',from:'18090000000',timestamp:String(Math.floor(Date.now()/1000)),text:{body:'Quiero información'}}]}}]}]};
  const raw=JSON.stringify(payload),signature='sha256='+createHmac('sha256',credentials.appSecret).update(raw).digest('hex');
  expect((await request(app).post(endpoint).send(payload)).status).toBe(403);
  for(let i=0;i<2;i++)expect((await request(app).post(endpoint).set('Content-Type','application/json').set('x-hub-signature-256',signature).send(raw)).status).toBe(200);
  const events=await prisma.channelEvent.findMany({where:{organizationId:orgA}});expect(events).toHaveLength(1);
  const blockedFetch=vi.spyOn(globalThis,'fetch').mockRejectedValue(Error('No external calls permitted'));
  await processSocialEvent(events[0].id);await processSocialEvent(events[0].id);expect(blockedFetch).not.toHaveBeenCalled();blockedFetch.mockRestore();
  const processed=await prisma.channelEvent.findUniqueOrThrow({where:{id:events[0].id}});expect(processed.status).toBe('NEEDS_HUMAN');expect(await prisma.message.count({where:{conversationId:processed.conversationId!}})).toBe(1);
  const draft=await post('/conversations/'+processed.conversationId+'/messages',{direction:'OUTBOUND',content:'Respuesta revisada'});
  const socialMock=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify({messages:[{id:'mock-social-provider-id'}]}),{status:200}));
  expect((await post('/messages/'+draft.body.item.id+'/send-social',{confirm:true})).status).toBe(200);
  expect((await post('/messages/'+draft.body.item.id+'/send-social',{confirm:true})).status).toBe(409);expect(socialMock).toHaveBeenCalledTimes(1);socialMock.mockRestore();
  expect(normalizeEvents({entry:[{id:'12345',messaging:[{sender:{id:'987'},recipient:{id:'12345'},timestamp:Date.now(),message:{mid:'echo',text:'Hola',is_echo:true}},{sender:{id:'987'},recipient:{id:'54321'},timestamp:Date.now(),message:{mid:'wrong',text:'Hola'}}]}]},'FACEBOOK','12345')).toHaveLength(0);
  // Auto replies are exercised against mocked providers only.
  expect((await a.put('/api/workspace/connections/GEMINI').set('x-organization-id',orgA).send({apiKey:'mock-gemini-test-key',model:'test-model'})).status).toBe(200);
  mockedGenerate.mockResolvedValue({text:'Hola, soy el asistente virtual. ¿Qué producto te interesa?'});
  expect((await a.put('/api/workspace/connections/WHATSAPP').set('x-organization-id',orgA).send({...credentials,autoReply:true})).status).toBe(200);
  const autoEvent=await prisma.channelEvent.create({data:{organizationId:orgA,provider:'WHATSAPP',externalId:'wamid-auto-2',payload:{accountId:'12345',sender:'18090000000',text:'Quiero conocer los productos',timestamp:Date.now()}}});
  const autoMock=vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify({messages:[{id:'mock-auto-id'}]}),{status:200}));
  await processSocialEvent(autoEvent.id);expect((await prisma.channelEvent.findUniqueOrThrow({where:{id:autoEvent.id}})).status).toBe('ACCEPTED');expect(autoMock).toHaveBeenCalledTimes(1);autoMock.mockRestore();
  expect((await a.patch('/api/workspace/conversations/'+processed.conversationId+'/mode').set('x-organization-id',orgA).send({status:'HUMAN'})).status).toBe(200);
  const humanEvent=await prisma.channelEvent.create({data:{organizationId:orgA,provider:'WHATSAPP',externalId:'wamid-human-3',payload:{accountId:'12345',sender:'18090000000',text:'Gracias',timestamp:Date.now()}}});
  const calls=mockedGenerate.mock.calls.length;await processSocialEvent(humanEvent.id);expect(mockedGenerate.mock.calls.length).toBe(calls);expect((await prisma.channelEvent.findUniqueOrThrow({where:{id:humanEvent.id}})).status).toBe('NEEDS_HUMAN');
  const website=await request(app).post('/api/website/'+orgA+'/'+policy.body.settings.widgetKey+'/chat').send({name:'Visitor',email:'visitor@example.test',consent:true,message:'Hola'});expect(website.status).toBe(200);expect(website.body.content).toContain('asistente virtual');expect(website.body.session).toBeTruthy();
  expect(await prisma.deal.count({where:{organizationId:orgA,title:'Consulta web: Visitor'}})).toBe(1);
  const courseProduct=await prisma.product.create({data:{organizationId:orgA,name:'Curso de prueba',price:12500,currency:'DOP',type:'COURSE',metadata:{preserve:'yes'}}});
  const knowledge={modules:'Módulo 1: Atención',syllabus:'Tema verificado de prueba',duration:'5 meses',schedule:'Sábados 10:00, America/Santo_Domingo',modality:'Virtual',requirements:'',fees:'Inscripción incluida en total',accreditations:'Sin aval confirmado',certificate:'',policies:'',sources:'Documento de prueba, revisión de hoy',validUntil:null,approved:false};
  const saveKnowledge=(body:any)=>a.put('/api/workspace/course-knowledge/'+courseProduct.id).set('x-organization-id',orgA).send(body);
  expect((await saveKnowledge(knowledge)).status).toBe(200);
  expect((await getAgentCatalogue(orgA)).find(p=>p.id===courseProduct.id)?.courseDetails).toBe(null);
  expect((await saveKnowledge({...knowledge,approved:true,sources:''})).status).toBe(400);
  expect((await saveKnowledge({...knowledge,approved:true})).status).toBe(200);
  expect((await getAgentCatalogue(orgA)).find(p=>p.id===courseProduct.id)?.courseDetails.syllabus).toBe('Tema verificado de prueba');
  expect((await prisma.product.findUniqueOrThrow({where:{id:courseProduct.id}})).metadata).toMatchObject({preserve:'yes'});
  expect((await b.put('/api/workspace/course-knowledge/'+courseProduct.id).set('x-organization-id',orgB).send(knowledge)).status).toBe(404);
  await prisma.product.update({where:{id:courseProduct.id},data:{price:13000}});
  expect((await getAgentCatalogue(orgA)).find(p=>p.id===courseProduct.id)?.courseDetails).toBe(null);
  expect((await saveKnowledge({...knowledge,approved:true,validUntil:'2000-01-01T00:00:00.000Z'})).status).toBe(200);
  expect((await getAgentCatalogue(orgA)).find(p=>p.id===courseProduct.id)?.courseDetails).toBe(null);
  const viewerEmail=`view-${stamp}@example.test`;
  expect((await a.post('/api/operations/team').set('x-organization-id',orgA).send({name:'Viewer',email:viewerEmail,password:'ViewerPassword123!',role:'VIEWER'})).status).toBe(201);
  const viewer=request.agent(app);await viewer.post('/api/auth/login').send({email:viewerEmail,password:'ViewerPassword123!'});
  expect((await viewer.get('/api/workspace/payments').set('x-organization-id',orgA)).status).toBe(403);
  expect((await viewer.post('/api/workspace/agents').set('x-organization-id',orgA).send({name:'Forbidden'})).status).toBe(403);
  expect((await viewer.get('/api/workspace/documents/'+proofDoc.id+'/download').set('x-organization-id',orgA)).status).toBe(403);
  const viewerDocs=await viewer.get('/api/workspace/documents').set('x-organization-id',orgA);expect(viewerDocs.body.items.some((d:any)=>d.id===proofDoc.id)).toBe(false);
  const saved=await a.get('/api/workspace/conversations').set('x-organization-id',orgA);expect(saved.body.items.find((c:any)=>c.id===conv.body.item.id).messages[0].status).toBe('ACCEPTED');
 },60000);
});
